<?php 
$json = json_decode($data);
$Title = $json -> Title;
$Articles = $json -> Articles;
echo '<!doctype html>';
echo '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">';
echo '<head>';
echo '<!-- NAME: MONTHLY CONTEST -->';
echo '<!--[if gte mso 15]>';
echo '<xml>';
echo '<o:OfficeDocumentSettings>';
echo '<o:AllowPNG/>';
echo '<o:PixelsPerInch>96</o:PixelsPerInch>';
echo '</o:OfficeDocumentSettings>';
echo '</xml>';
echo '<![endif]-->';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>*|MC:SUBJECT|*</title>';
echo '';
echo '<style type="text/css">';
echo 'p{';
echo 'margin:10px 0;';
echo 'padding:0;';
echo '}';
echo 'table{';
echo 'border-collapse:collapse;';
echo '}';
echo 'h1,h2,h3,h4,h5,h6{';
echo 'display:block;';
echo 'margin:0;';
echo 'padding:0;';
echo '}';
echo 'img,a img{';
echo 'border:0;';
echo 'height:auto;';
echo 'outline:none;';
echo 'text-decoration:none;';
echo '}';
echo 'body,#bodyTable,#bodyCell{';
echo 'height:100%;';
echo 'margin:0;';
echo 'padding:0;';
echo 'width:100%;';
echo '}';
echo '.mcnPreviewText{';
echo 'display:none !important;';
echo '}';
echo '#outlook a{';
echo 'padding:0;';
echo '}';
echo 'img{';
echo '-ms-interpolation-mode:bicubic;';
echo '}';
echo 'table{';
echo 'mso-table-lspace:0pt;';
echo 'mso-table-rspace:0pt;';
echo '}';
echo '.ReadMsgBody{';
echo 'width:100%;';
echo '}';
echo '.ExternalClass{';
echo 'width:100%;';
echo '}';
echo 'p,a,li,td,blockquote{';
echo 'mso-line-height-rule:exactly;';
echo '}';
echo 'a[href^=tel],a[href^=sms]{';
echo 'color:inherit;';
echo 'cursor:default;';
echo 'text-decoration:none;';
echo '}';
echo 'p,a,li,td,body,table,blockquote{';
echo '-ms-text-size-adjust:100%;';
echo '-webkit-text-size-adjust:100%;';
echo '}';
echo '.ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{';
echo 'line-height:100%;';
echo '}';
echo 'a[x-apple-data-detectors]{';
echo 'color:inherit !important;';
echo 'text-decoration:none !important;';
echo 'font-size:inherit !important;';
echo 'font-family:inherit !important;';
echo 'font-weight:inherit !important;';
echo 'line-height:inherit !important;';
echo '}';
echo '#bodyCell{';
echo 'padding:10px;';
echo '}';
echo '.templateContainer{';
echo 'max-width:600px !important;';
echo '}';
echo 'a.mcnButton{';
echo 'display:block;';
echo '}';
echo '.mcnImage,.mcnRetinaImage{';
echo 'vertical-align:bottom;';
echo '}';
echo '.mcnTextContent{';
echo 'word-break:break-word;';
echo '}';
echo '.mcnTextContent img{';
echo 'height:auto !important;';
echo '}';
echo '.mcnDividerBlock{';
echo 'table-layout:fixed !important;';
echo '}';
echo 'body,#bodyTable{';
echo 'background-color:#ffffff;';
echo '}';
echo '#bodyCell{';
echo 'border-top:0;';
echo '}';
echo '.templateContainer{';
echo 'border:0;';
echo '}';
echo 'h1{';
echo 'color:#222222;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:32px;';
echo 'font-style:normal;';
echo 'font-weight:bold;';
echo 'line-height:125%;';
echo 'letter-spacing:normal;';
echo 'text-align:center;';
echo '}';
echo 'h2{';
echo 'color:#222222;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:22px;';
echo 'font-style:normal;';
echo 'font-weight:bold;';
echo 'line-height:125%;';
echo 'letter-spacing:normal;';
echo 'text-align:left;';
echo '}';
echo 'h3{';
echo 'color:#FFFFFF;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:20px;';
echo 'font-style:normal;';
echo 'font-weight:bold;';
echo 'line-height:125%;';
echo 'letter-spacing:normal;';
echo 'text-align:left;';
echo '}';
echo 'h4{';
echo 'color:#FFFFFF;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:14px;';
echo 'font-style:normal;';
echo 'font-weight:normal;';
echo 'line-height:125%;';
echo 'letter-spacing:2px;';
echo 'text-align:center;';
echo '}';
echo '#templatePreheader{';
echo 'background-color:#ffffff;';
echo 'background-image:none;';
echo 'background-repeat:no-repeat;';
echo 'background-position:center;';
echo 'background-size:cover;';
echo 'border-top:0;';
echo 'border-bottom:0;';
echo 'padding-top:9px;';
echo 'padding-bottom:9px;';
echo '}';
echo '#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
echo 'color:#222222;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:12px;';
echo 'line-height:150%;';
echo 'text-align:left;';
echo '}';
echo '#templatePreheader .mcnTextContent a,#templatePreheader .mcnTextContent p a{';
echo 'color:#d03837;';
echo 'font-weight:normal;';
echo 'text-decoration:underline;';
echo '}';
echo '#templateHeader{';
echo 'background-color:#222222;';
echo 'background-image:url("https://mcusercontent.com/de0f5a5febafb248cac8e87d7/images/515a59ab-9d75-e192-bb43-62471673b04f.png");';
echo 'background-repeat:no-repeat;';
echo 'background-position:bottom;';
echo 'background-size:cover;';
echo 'border-top:0;';
echo 'border-bottom:0;';
echo 'padding-top:40px;';
echo 'padding-bottom:40px;';
echo '}';
echo '#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
echo 'color:#FFFFFF;';
echo 'font-family:Georgia, Times, "Times New Roman", serif;';
echo 'font-size:18px;';
echo 'line-height:150%;';
echo 'text-align:center;';
echo '}';
echo '#templateHeader .mcnTextContent a,#templateHeader .mcnTextContent p a{';
echo 'color:#d03837;';
echo 'font-weight:normal;';
echo 'text-decoration:underline;';
echo '}';
echo '#templateBody{';
echo 'background-color:#ffffff;';
echo 'background-image:none;';
echo 'background-repeat:no-repeat;';
echo 'background-position:bottom;';
echo 'background-size:cover;';
echo 'border-top:0;';
echo 'border-bottom:0;';
echo 'padding-top:40px;';
echo 'padding-bottom:10px;';
echo '}';
echo '#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
echo 'color:#222222;';
echo 'font-family:"Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;';
echo 'font-size:18px;';
echo 'line-height:150%;';
echo 'text-align:left;';
echo '}';
echo '#templateBody .mcnTextContent a,#templateBody .mcnTextContent p a{';
echo 'color:#d03837;';
echo 'font-weight:normal;';
echo 'text-decoration:underline;';
echo '}';
echo '#templateFooter{';
echo 'background-color:#ffffff;';
echo 'background-image:none;';
echo 'background-repeat:no-repeat;';
echo 'background-position:center;';
echo 'background-size:cover;';
echo 'border-top:0;';
echo 'border-bottom:0;';
echo 'padding-top:20px;';
echo 'padding-bottom:40px;';
echo '}';
echo '#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
echo 'color:#656565;';
echo 'font-family:Helvetica;';
echo 'font-size:12px;';
echo 'line-height:150%;';
echo 'text-align:center;';
echo '}';
echo '#templateFooter .mcnTextContent a,#templateFooter .mcnTextContent p a{';
echo 'color:#656565;';
echo 'font-weight:normal;';
echo 'text-decoration:underline;';
echo '}';
echo '@media only screen and (min-width:768px){';
echo '.templateContainer{';
echo 'width:600px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'body,table,td,p,a,li,blockquote{';
echo '-webkit-text-size-adjust:none !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'body{';
echo 'width:100% !important;';
echo 'min-width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#bodyCell{';
echo 'padding-top:10px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnRetinaImage{';
echo 'max-width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImage{';
echo 'width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnCartContainer,.mcnCaptionTopContent,.mcnRecContentContainer,.mcnCaptionBottomContent,.mcnTextContentContainer,.mcnBoxedTextContentContainer,.mcnImageGroupContentContainer,.mcnCaptionLeftTextContentContainer,.mcnCaptionRightTextContentContainer,.mcnCaptionLeftImageContentContainer,.mcnCaptionRightImageContentContainer,.mcnImageCardLeftTextContentContainer,.mcnImageCardRightTextContentContainer,.mcnImageCardLeftImageContentContainer,.mcnImageCardRightImageContentContainer{';
echo 'max-width:100% !important;';
echo 'width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnBoxedTextContentContainer{';
echo 'min-width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageGroupContent{';
echo 'padding:9px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnCaptionLeftContentOuter .mcnTextContent,.mcnCaptionRightContentOuter .mcnTextContent{';
echo 'padding-top:9px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageCardTopImageContent,.mcnCaptionBottomContent:last-child .mcnCaptionBottomImageContent,.mcnCaptionBlockInner .mcnCaptionTopContent:last-child .mcnTextContent{';
echo 'padding-top:18px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageCardBottomImageContent{';
echo 'padding-bottom:9px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageGroupBlockInner{';
echo 'padding-top:0 !important;';
echo 'padding-bottom:0 !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageGroupBlockOuter{';
echo 'padding-top:9px !important;';
echo 'padding-bottom:9px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnTextContent,.mcnBoxedTextContentColumn{';
echo 'padding-right:18px !important;';
echo 'padding-left:18px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnImageCardLeftImageContent,.mcnImageCardRightImageContent{';
echo 'padding-right:18px !important;';
echo 'padding-bottom:0 !important;';
echo 'padding-left:18px !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcpreview-image-uploader{';
echo 'display:none !important;';
echo 'width:100% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'h1{';
echo 'font-size:22px !important;';
echo 'line-height:125% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'h2{';
echo 'font-size:20px !important;';
echo 'line-height:125% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'h3{';
echo 'font-size:18px !important;';
echo 'line-height:125% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo 'h4{';
echo 'font-size:16px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '.mcnBoxedTextContentContainer .mcnTextContent,.mcnBoxedTextContentContainer .mcnTextContent p{';
echo 'font-size:14px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#templatePreheader{';
echo 'display:block !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
echo 'font-size:14px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
echo 'font-size:16px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
echo 'font-size:16px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}	@media only screen and (max-width: 480px){';
echo '#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
echo 'font-size:14px !important;';
echo 'line-height:150% !important;';
echo '}';
echo '';
echo '}</style><!--[if !mso]><!--><link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i|Roboto:400,400i,700,700i" rel="stylesheet"><!--<![endif]--></head>';
echo '<body style="height: 100%;margin: 0;padding: 0;width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;">';
echo '<!--*|IF:MC_PREVIEW_TEXT|*-->';
echo '<!--[if !gte mso 9]><!----><span class="mcnPreviewText" style="display:none; font-size:0px; line-height:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility:hidden; mso-hide:all;">*|MC_PREVIEW_TEXT|*</span><!--<![endif]-->';
echo '<!--*|END:IF|*-->';
echo '<center>';
echo '<table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 0;width: 100%;background-color: #ffffff;">';
echo '<tr>';
echo '<td align="center" valign="top" id="bodyCell" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 10px;width: 100%;border-top: 0;">';
echo '<!-- BEGIN TEMPLATE // -->';
echo '<!--[if (gte mso 9)|(IE)]>';
echo '<table align="center" border="0" cellspacing="0" cellpadding="0" width="600" style="width:600px;">';
echo '<tr>';
echo '<td align="center" valign="top" width="600" style="width:600px;">';
echo '<![endif]-->';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: 0;max-width: 600px !important;">';
echo '<tr>';
echo '<td valign="top" id="templatePreheader" style="background:#ffffff none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnTextBlockOuter">';
echo '<tr>';
echo '<td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<!--[if mso]>';
echo '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
echo '<tr>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td valign="top" width="600" style="width:600px;">';
echo '<![endif]-->';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
echo '<tbody><tr>';
echo '';
echo '<td valign="top" class="mcnTextContent" style="padding: 0px 18px 9px;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 12px;line-height: 150%;">';
echo '';
echo '<a href="*|ARCHIVE|*" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #d03837;font-weight: normal;text-decoration: underline;">View this email in your browser</a>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table></td>';
echo '</tr>';
echo '<tr>';
echo '<td valign="top" id="templateHeader" style="background:#222222 url(&quot;https://mcusercontent.com/de0f5a5febafb248cac8e87d7/images/515a59ab-9d75-e192-bb43-62471673b04f.png&quot;) no-repeat bottom/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #222222;background-image: url(https://mcusercontent.com/de0f5a5febafb248cac8e87d7/images/515a59ab-9d75-e192-bb43-62471673b04f.png);background-repeat: no-repeat;background-position: bottom;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 40px;padding-bottom: 40px;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnImageBlockOuter">';
echo '<tr>';
echo '<td valign="top" style="padding: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnImageBlockInner">';
echo '<table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td class="mcnImageContent" valign="top" style="padding-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom: 0;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '';
echo '<img align="center" alt="" src="https://mcusercontent.com/de0f5a5febafb248cac8e87d7/images/66f52fe4-e4cc-436e-b259-d10772ab6e1c.png" width="236.88" style="max-width: 731px;padding-bottom: 0;display: inline !important;vertical-align: bottom;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" class="mcnImage">';
echo '';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnImageBlockOuter">';
echo '<tr>';
echo '<td valign="top" style="padding: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnImageBlockInner">';
echo '<table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td class="mcnImageContent" valign="top" style="padding-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom: 0;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '';
echo '<img align="center" alt="" src="https://mcusercontent.com/de0f5a5febafb248cac8e87d7/images/f2f94ced-2e64-4a41-b134-8cd91ae6696d.png" width="377.88" style="max-width: 1200px;padding-bottom: 0;display: inline !important;vertical-align: bottom;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" class="mcnImage">';
echo '';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table></td>';
echo '</tr>';
echo '<tr>';
echo '<td valign="top" id="templateBody" style="background:#ffffff none no-repeat bottom/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;background-image: none;background-repeat: no-repeat;background-position: bottom;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 40px;padding-bottom: 10px;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnTextBlockOuter">';
echo '<tr>';
echo '<td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<!--[if mso]>';
echo '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
echo '<tr>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td valign="top" width="600" style="width:600px;">';
echo '<![endif]-->';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
echo '<tbody><tr>';
echo '';
echo '<td valign="top" class="mcnTextContent" style="padding-top: 0;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 18px;line-height: 150%;text-align: left;">';
echo '';
echo '<h1 class="null" style="text-align: center;display: block;margin: 0;padding: 0;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 32px;font-style: normal;font-weight: bold;line-height: 125%;letter-spacing: normal;"><strong><font face="roboto, helvetica neue, helvetica, arial, sans-serif">'; 
echo $Title; 
echo '</font></strong></h1>';
echo '';
echo '<p style="text-align: left;margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 18px;line-height: 150%;"><em>Each weekday, we make available to all&nbsp;<strong>Trinity Forum Society</strong>&nbsp;members our brief&nbsp;curated list of&nbsp;reading recommendations&nbsp;in the areas of faith and spirituality, culture,&nbsp;the arts and humanities, politics, and social science. Below is a list of readings we think you’ll find of value.​</em></p>';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;table-layout: fixed !important;">';
echo '<tbody class="mcnDividerBlockOuter">';
echo '<tr>';
echo '<td class="mcnDividerBlockInner" style="min-width: 100%;padding: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-top-width: 2px;border-top-style: solid;border-top-color: #D03837;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<span></span>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '<!--';
echo '<td class="mcnDividerBlockInner" style="padding: 18px;">';
echo '<hr class="mcnDividerContent" style="border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;" />';
echo '-->';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
foreach($Articles as $key => $value) {
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnTextBlockOuter">';
echo '<tr>';
echo '<td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<!--[if mso]>';
echo '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
echo '<tr>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td valign="top" width="600" style="width:600px;">';
echo '<![endif]-->';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
echo '<tbody><tr>';
echo '';
echo '<td valign="top" class="mcnTextContent" style="padding: 0px 18px 9px;line-height: 150%;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 18px;text-align: left;">';
echo '';
echo '<a href='; 
echo  $value -> Link;
echo 'target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #d03837;font-weight: normal;text-decoration: underline;"><strong><span style="font-size:20px">';
echo  $value -> Title_html;
echo '</span></strong></a><br>';
echo '<font size="4">SOURCE:&nbsp;</font><span style="font-size:18px">';
echo $value-> Newsource_html;
echo '</span><br>';
echo '<font size="4">BYLINE:&nbsp;</font><span style="font-size:18px"><span data-sheets-userformat="{&quot;2&quot;:769,&quot;3&quot;:{&quot;1&quot;:0},&quot;11&quot;:4,&quot;12&quot;:0}" data-sheets-value="{&quot;1&quot;:2,&quot;2&quot;:&quot;Ross Douthat&quot;}">';
echo $value -> Byline_html;
echo '</span></span>';
echo '';
echo '<p dir="ltr" style="line-height: 150%;margin: 10px 0;padding: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;color: #222222;font-family: "Roboto", "Helvetica Neue", Helvetica, Arial, sans-serif;font-size: 18px;text-align: left;">';
echo $value -> Summary_html;
echo '<br>';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table>';
}
echo '</td>';
echo '</tr>';
echo '<tr>';
echo '<td valign="top" id="templateFooter" style="background:#ffffff none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 20px;padding-bottom: 40px;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnFollowBlockOuter">';
echo '<tr>';
echo '<td align="center" valign="top" style="padding: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowBlockInner">';
echo '<table width="100%" border="0" cellpadding="0" cellspacing="0" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="center" style="padding-left: 9px;padding-right: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentContainer">';
echo '<tbody><tr>';
echo '<td align="center" valign="top" style="padding: 10px;background-color: #D03837;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContent">';
echo '<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="top" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '<tbody><tr>';
echo '';
echo '';
echo '<td valign="middle" class="mcnFollowTextContent" style="padding-left: 0;padding-bottom: 10px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://www.ttf.org/shop/" target="_blank" style="color: #FFFFFF;font-family: &quot;Playfair Display&quot;, Georgia, &quot;Times New Roman&quot;, serif;font-size: 12px;font-weight: bold;text-decoration: none;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">READINGS</a>';
echo '</td>';
echo '';
echo '</tr>';
echo '';
echo '';
echo '</tbody></table>';
echo '';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '<tbody><tr>';
echo '';
echo '';
echo '<td valign="middle" class="mcnFollowTextContent" style="padding-left: 0;padding-bottom: 10px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://www.ttf.org/upcoming-events/" target="_blank" style="color: #FFFFFF;font-family: &quot;Playfair Display&quot;, Georgia, &quot;Times New Roman&quot;, serif;font-size: 12px;font-weight: bold;text-decoration: none;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">UPCOMING EVENTS</a>';
echo '</td>';
echo '';
echo '</tr>';
echo '';
echo '';
echo '</tbody></table>';
echo '';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '<tbody><tr>';
echo '';
echo '';
echo '<td valign="middle" class="mcnFollowTextContent" style="padding-left: 0;padding-bottom: 10px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://www.ttf.org/about-us/senior-fellows/" target="_blank" style="color: #FFFFFF;font-family: &quot;Playfair Display&quot;, Georgia, &quot;Times New Roman&quot;, serif;font-size: 12px;font-weight: bold;text-decoration: none;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">SENIOR FELLOWS</a>';
echo '</td>';
echo '';
echo '</tr>';
echo '';
echo '';
echo '</tbody></table>';
echo '';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '';
echo '<tbody><tr>';
echo '';
echo '';
echo '<td valign="middle" class="mcnFollowTextContent" style="padding-left: 0;padding-bottom: 0;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://ttf.org/civicrm?page=CiviCRM&q=civicrm/contribute/transact&reset=1&id=2" target="_blank" style="color: #FFFFFF;font-family: &quot;Playfair Display&quot;, Georgia, &quot;Times New Roman&quot;, serif;font-size: 12px;font-weight: bold;text-decoration: none;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">GIVE</a>';
echo '</td>';
echo '';
echo '</tr>';
echo '';
echo '';
echo '</tbody></table>';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnFollowBlockOuter">';
echo '<tr>';
echo '<td align="center" valign="top" style="padding: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowBlockInner">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentContainer" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="center" style="padding-left: 9px;padding-right: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContent">';
echo '<tbody><tr>';
echo '<td align="center" valign="top" style="padding-top: 9px;padding-right: 9px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="center" valign="top" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<!--[if mso]>';
echo '<table align="center" border="0" cellspacing="0" cellpadding="0">';
echo '<tr>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td align="center" valign="top">';
echo '<![endif]-->';
echo '';
echo '';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td valign="top" style="padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentItemContainer">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="middle" style="padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '';
echo '<td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://www.facebook.com/trinityforum/" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/outline-dark-facebook-48.png" alt="Facebook" style="display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" height="24" width="24" class=""></a>';
echo '</td>';
echo '';
echo '';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td align="center" valign="top">';
echo '<![endif]-->';
echo '';
echo '';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td valign="top" style="padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentItemContainer">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="middle" style="padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '';
echo '<td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://twitter.com/TRINITYFORUM" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/outline-dark-twitter-48.png" alt="Twitter" style="display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" height="24" width="24" class=""></a>';
echo '</td>';
echo '';
echo '';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td align="center" valign="top">';
echo '<![endif]-->';
echo '';
echo '';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td valign="top" style="padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentItemContainer">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="middle" style="padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '';
echo '<td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="http://instagram.com/TRINITYFORUM" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/outline-dark-instagram-48.png" alt="Instagram" style="display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" height="24" width="24" class=""></a>';
echo '</td>';
echo '';
echo '';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td align="center" valign="top">';
echo '<![endif]-->';
echo '';
echo '';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td valign="top" style="padding-right: 10px;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentItemContainer">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="middle" style="padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '';
echo '<td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="http://ttf.org" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/outline-dark-link-48.png" alt="Website" style="display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" height="24" width="24" class=""></a>';
echo '</td>';
echo '';
echo '';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td align="center" valign="top">';
echo '<![endif]-->';
echo '';
echo '';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="display: inline;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td valign="top" style="padding-right: 0;padding-bottom: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnFollowContentItemContainer">';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnFollowContentItem" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '<td align="left" valign="middle" style="padding-top: 5px;padding-right: 10px;padding-bottom: 5px;padding-left: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" width="" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody><tr>';
echo '';
echo '<td align="center" valign="middle" width="24" class="mcnFollowIconContent" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<a href="https://www.youtube.com/channel/UCdrg24mRqoGVKuXGvqCjNZA" target="_blank" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;"><img src="https://cdn-images.mailchimp.com/icons/social-block-v2/outline-dark-youtube-48.png" alt="YouTube" style="display: block;border: 0;height: auto;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;" height="24" width="24" class=""></a>';
echo '</td>';
echo '';
echo '';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<tbody class="mcnTextBlockOuter">';
echo '<tr>';
echo '<td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
echo '<!--[if mso]>';
echo '<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
echo '<tr>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '<td valign="top" width="600" style="width:600px;">';
echo '<![endif]-->';
echo '<table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
echo '<tbody><tr>';
echo '';
echo '<td valign="top" class="mcnTextContent" style="padding-top: 0;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #656565;font-family: Helvetica;font-size: 12px;line-height: 150%;text-align: center;">';
echo '';
echo '<em>Copyright © The Trinity Forum 2023</em><br>';
echo '<br>';
echo '1015 18th Street NW<br>';
echo 'Suite 201<br>';
echo 'Washington, DC 20036';
echo '</td>';
echo '</tr>';
echo '</tbody></table>';
echo '<!--[if mso]>';
echo '</td>';
echo '<![endif]-->';
echo '';
echo '<!--[if mso]>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '</td>';
echo '</tr>';
echo '</tbody>';
echo '</table></td>';
echo '</tr>';
echo '</table>';
echo '<!--[if (gte mso 9)|(IE)]>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<![endif]-->';
echo '<!-- // END TEMPLATE -->';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</center>';
echo '<center>';
echo '<br />';
echo '<br />';
echo '<br />';
echo '<br />';
echo '<br />';
echo '<br />';
echo '<table border="0" cellpadding="0" cellspacing="0" width="100%" id="canspamBarWrapper" style="background-color:#FFFFFF; border-top:1px solid #E5E5E5;">';
echo '<tr>';
echo '<td align="center" valign="top" style="padding-top:20px; padding-bottom:20px;">';
echo '<table border="0" cellpadding="0" cellspacing="0" id="canspamBar">';
echo '<tr>';
echo '<td align="center" valign="top" style="color:#606060; font-family:Helvetica, Arial, sans-serif; font-size:11px; line-height:150%; padding-right:20px; padding-bottom:5px; padding-left:20px; text-align:center;">';
echo 'This email was sent to <a href="mailto:*|EMAIL|*" target="_blank" style="color:#404040 !important;">*|EMAIL|*</a>';
echo '<br />';
echo '<a href="*|ABOUT_LIST|*" target="_blank" style="color:#404040 !important;"><em>why did I get this?</em></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="*|UNSUB|*" style="color:#404040 !important;">unsubscribe from this list</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="*|UPDATE_PROFILE|*" style="color:#404040 !important;">update subscription preferences</a>';
echo '<br />';
echo '*|LIST:ADDRESSLINE|*';
echo '<br />';
echo '<br />';
echo '';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '<style type="text/css">';
echo '@media only screen and (max-width: 480px){';
echo 'table#canspamBar td{font-size:14px !important;}';
echo 'table#canspamBar td a{display:block !important; margin-top:10px !important;}';
echo '}';
echo '</style>';
echo '</center></body>';
echo '</html>';
echo '';
?>